// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	KmsKeysCreateOperation   OperationName = "KmsKeysCreate"
	KmsKeysDestroyOperation  OperationName = "KmsKeysDestroy"
	KmsKeysListOperation     OperationName = "KmsKeysList"
	KmsKeysRetrieveOperation OperationName = "KmsKeysRetrieve"
	KmsKeysUpdateOperation   OperationName = "KmsKeysUpdate"
)
