// Code generated by ogen, DO NOT EDIT.

package v1

// KmsKeysDestroyParams is parameters of kms_keys_destroy operation.
type KmsKeysDestroyParams struct {
	ResourceID string
}

// KmsKeysRetrieveParams is parameters of kms_keys_retrieve operation.
type KmsKeysRetrieveParams struct {
	ResourceID string
}

// KmsKeysUpdateParams is parameters of kms_keys_update operation.
type KmsKeysUpdateParams struct {
	ResourceID string
}
